# Generated by Django 3.2.9 on 2021-11-16 08:30

import datetime

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.date(2021, 11, 16)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='random_number',
            field=models.PositiveSmallIntegerField(default=users.models.generate_random_number),
        ),
    ]
